## 
# This script constructs a panel with hat stiffeners
##

# All measures currently in inches and degrees


# First build the plate
set plate_width    10.25
set plate_length    7.5
set plate_thickness 0.0625

set plate_origin_x 0.0
set plate_origin_y 0.0
set plate_origin_z 0.0

box plate_origin_x plate_origin_y plate_origin_z plate_width plate_length plate_thickness
store plate

# Construct the hat stiffeners
set stiffener_thickness     0.032
set stiffener_foot_width    0.640852
set stiffener_rise_angle   60.0
set stiffener_depth         1.0
set stiffener_length        5.5
set stiffener_inner_radius 0.125
set stiffener_base_interior_width 2.356523

set stiffener_origin_x 0.0
set stiffener_origin_y 0.0
set stiffener_origin_z 0.0

set stiffener_fillet_out_radius stiffener_inner_radius+stiffener_thickness
set stiffener_fillet_out_hypot  2*stiffener_fillet_out_radius*sind(stiffener_rise_angle/2.0)
set stiffener_fillet_out_x      stiffener_fillet_out_hypot*cosd(90-stiffener_rise_angle/2.0)
set stiffener_fillet_out_y      stiffener_fillet_out_hypot*sind(90-stiffener_rise_angle/2.0)

set stiffener_fillet_in_radius stiffener_inner_radius
set stiffener_fillet_in_hypot  2*stiffener_fillet_in_radius*sind(stiffener_rise_angle/2.0)
set stiffener_fillet_in_x      stiffener_fillet_in_hypot*cosd(90-stiffener_rise_angle/2.0)
set stiffener_fillet_in_y      stiffener_fillet_in_hypot*sind(90-stiffener_rise_angle/2.0)

set stiffener_arc_in_dist  stiffener_fillet_in_radius*sind(stiffener_rise_angle/2.0)/tand(90.0-stiffener_rise_angle/4.0)
set stiffener_arc_out_dist stiffener_fillet_out_radius*sind(stiffener_rise_angle/2.0)/tand(90.0-stiffener_rise_angle/4.0)

skbeg stiffener_origin_x\
      stiffener_origin_y\
      stiffener_origin_z
  # Going left to right along bottom
  # 1
  linseg stiffener_origin_x+stiffener_foot_width\
         stiffener_origin_y\
         stiffener_origin_z
  # 2
  arc stiffener_origin_x+stiffener_foot_width+stiffener_fillet_out_x\
      stiffener_origin_y+stiffener_fillet_out_y\
      stiffener_origin_z \
      stiffener_arc_out_dist

skend
# extrude   0.0 0.0 stiffener_length 

end

rotatex  90.0 0.0 0.0
translate 0.0 7.5 plate_thickness
store stiffener

# Place the panel face and stiffeners on it
set num_stiffeners    2.0
set stiffener_offset  0.35875
set stiffener_spacing 0.717

set dx                    stiffener_offset
# set stiffener_total_width 2*stiffener_foot_width+2*stiffener_wall_lean+stiffener_base_interior_width
patbeg i num_stiffeners
  restore stiffener
  translate dx 0.0 0.0
  set dx dx+stiffener_total_width+stiffener_offset
patend
restore plate

