#!/bin/sh

export TRILINOS_INSTALL_DIR=/lore/maxim/trilinos_nightly/install

cmake \
 -D ALBANY_TRILINOS_DIR:FILEPATH="$TRILINOS_INSTALL_DIR" \
 -D ENABLE_SCOREC:BOOL=ON \
 -D ENABLE_LCM:BOOL=ON \
 -D ENABLE_CTM:BOOL=OFF \
 -D ENABLE_AMP:BOOL=OFF \
 -D ENABLE_ANISO:BOOL=OFF \
 -D ENABLE_OMEGA_H:BOOL=OFF \
 -D ENABLE_QCAD:BOOL=OFF \
 -D ENABLE_LCM_SPECULATIVE:BOOL=OFF \
 -D ENABLE_LAME:BOOL=OFF \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
 -D ENABLE_DEBUGGING:BOOL=OFF \
 -D ENABLE_CHECK_FPE:BOOL=ON \
 -D Albany_DEPRECATED_DECLARATIONS:BOOL=ON \
 -D ENABLE_HYDRIDE:BOOL=OFF \
 -D ENABLE_FELIX:BOOL=OFF \
 -D ENABLE_MOR:BOOL=OFF \
 -D ENABLE_ALBANY_CI:BOOL=OFF \
 -D ENABLE_ASCR:BOOL=OFF \
 -D ENABLE_64BIT_INT:BOOL=ON \
 -D ENABLE_ALBANY_EPETRA_EXE:BOOL=OFF \
 -D ENABLE_STK:BOOL=OFF \
 .. \
 2>&1 | tee config_log
