#!/bin/sh

export ALB_FLAGS="-Wno-deprecated-declarations"
export ALB_64BIT_INT=OFF
export ALB_EPETRA=ON
export ALB_ENABLE_SCOREC=ON
export ALB_ENABLE_LCM=ON
export ALB_ENABLE_LAME=OFF
export ALB_ENABLE_HYDRIDE=OFF
export ALB_ENABLE_QCAD=OFF
export ALB_ENABLE_MOR=OFF
export ALB_ENABLE_ASCR=OFF
export ALB_ENABLE_AERAS=OFF
export ALB_ENABLE_LANDICE=OFF
export ALB_ENABLE_AlbanyCI=OFF
export ALB_DEBUG=ON
export ALB_ENABLE_CHECK_FPE=OFF
export ALB_FLUSH_DENORMALS=ON
export ALB_ENABLE_SPECULATIVE=OFF
export ALB_ENABLE_SG_MP=OFF
export ALB_ENABLE_PERF_TESTS=ON
export TRILINOS_INSTALL_DIR=/usr/local/
export ALB_VERBOSE=ON

cmake \
      -D ALBANY_TRILINOS_DIR:FILEPATH="$TRILINOS_INSTALL_DIR" \
      -D ENABLE_LCM:BOOL=${ALB_ENABLE_LCM} \
      -D ENABLE_AERAS:BOOL=${ALB_ENABLE_AERAS} \
      -D ENABLE_QCAD:BOOL=${ALB_ENABLE_QCAD} \
      -D ENABLE_HYDRIDE:BOOL=${ALB_ENABLE_HYDRIDE} \
      -D ENABLE_LCM_SPECULATIVE:BOOL=${ALB_ENABLE_SPECULATIVE} \
      -D ENABLE_LAME:BOOL=${ALB_ENABLE_LAME} \
      -D CMAKE_VERBOSE_MAKEFILE:BOOL=${ALB_VERBOSE} \
      -D ENABLE_DEBUGGING:BOOL=${ALB_DEBUG} \
      -D ENABLE_CHECK_FPE:BOOL=${ALB_ENABLE_CHECK_FPE} \
      -D ENABLE_FLUSH_DENORMALS:BOOL=${ALB_FLUSH_DENORMALS} \
      -D ENABLE_SCOREC:BOOL=${ALB_ENABLE_SCOREC} \
      -D ENABLE_LANDICE:BOOL=${ALB_ENABLE_LANDICE} \
      -D ENABLE_MOR:BOOL=${ALB_ENABLE_MOR} \
      -D ENABLE_ALBANY_CI:BOOL=${ALB_ENABLE_AlbanyCI} \
      -D ENABLE_ASCR:BOOL=${ALB_ENABLE_ASCR} \
      -D ENABLE_SG_MP:BOOL=${ALB_ENABLE_SG_MP} \
      -D ENABLE_PERFORMANCE_TESTS:BOOL=${ALB_ENABLE_PERF_TESTS} \
      -D ENABLE_64BIT_INT:BOOL=${ALB_64BIT_INT} \
      -D ENABLE_ALBANY_EPETRA_EXE:BOOL=${ALB_EPETRA} \
      -D CMAKE_EXE_LINKER_FLAGS:STRING="-lgfortran" \
\
.. \
\
2>&1 | tee config_log

